### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f44b' in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by toolgood** [Akegarasu/ChatGLM-webui#11]
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f44b' in position 2: illegal multibyte sequence

**Comment by Akegarasu** [comment]
need more info.

**Comment by toolgood** [comment]
```
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components.py:148: UserWarning: Unknown style parameter: height
  warnings.warn(f"Unknown style parameter: {key}")

```

**Comment by toolgood** [comment]
```
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\git\ChatGLM-webui\modules\ui.py", line 16, in predict
    _, output = infer(
  File "E:\git\ChatGLM-webui\modules\model.py", line 55, in infer
    print(output)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f44b' in position 2: illegal multibyte sequence

```

**Comment by toolgood** [comment]
加载成功后，能不能自动使用浏览器打开网址
